### ISSUE TITLE
SVG Parser: Port @lautr3k 's parser from LW3:Optimisation branch

### ISSUE THREAD

**Issue by cojarbi** [LaserWeb/LaserWeb4#58] opened 2016-12-08 13:00 UTC
Not sure the reason nor the difference but some open for me some dont.

[CUT LETRAS does not open.svg.txt](https://github.com/LaserWeb/LaserWeb4/files/639446/CUT.LETRAS.does.not.open.svg.txt)
[color boxes does not open.svg.txt](https://github.com/LaserWeb/LaserWeb4/files/639448/color.boxes.does.not.open.svg.txt)
[A does open.svg.txt](https://github.com/LaserWeb/LaserWeb4/files/639450/A.does.open.svg.txt)

**Comment by lautr3k** [comment] 2016-12-08 13:04
Need to port my SVG parser to ES6.

**Comment by tbfleming** [comment] 2016-12-08 13:29
"A": May be another OSX issue:
<img width="277" alt="a" src="https://cloud.githubusercontent.com/assets/418464/21011642/2b565fc2-bd20-11e6-85f9-19edd07a1d80.png">

"CUTLETRAS" and "color boxes": No path objects. Current parser only handles groups and paths.

@lautr3k does your parser handle non-path objects?

**Comment by tbfleming** [comment] 2016-12-08 13:32
@cojarbi Check Settings -> File Settings -> SVG PX PER INCH. It should have defaulted to 96, but if the defaults didn't initialize properly (e.g. empty or 0) then it may mess up the parser.

**Comment by lautr3k** [comment] 2016-12-08 13:44
@tbfleming my SVG parser curently support all basics shapes (line, polyline, polygone, rect, circle, arc, ellipse), all paths commands, group, viewBox, defs and use.

**Comment by lautr3k** [comment] 2016-12-08 13:46
Just created the repo for the ES6 rewrite as NMP module : https://github.com/lautr3k/lw.svg-parser

**Comment by openhardwarecoza** [comment] 2016-12-08 13:51
(: we also really need the dxf parser to come over.  I still hate svgs (;

**Comment by cojarbi** [comment] 2016-12-08 14:07
@tbfleming Settings are on the default 96

**Comment by lautr3k** [comment] 2016-12-08 14:10
@tbfleming I can not find any more you said the format for the paths...
```
path1 = [
    [x,y,x,y,x,y], // Shape or Line
    [x,y,x,y,x,y]  // Hole if shape
    ...            // Hole...
]
```
```
path2 = [
    [[x,y],[x,y],[x,y]], // Shape or Line
    [[x,y],[x,y],[x,y]]  // Hole if shape
    ...                  // Hole...
]
```
I think path1 ?

**Comment by tbfleming** [comment] 2016-12-08 14:52
path1. It can be a mix of open and closed subpaths and the outer order doesn't matter. e.g. this is valid:
```
path1 = [
    [x,y,x,y,x,y,...], // Open path
    [x,y,x,y,x,y,...], // Closed path for a hole
    [x,y,x,y,x,y,...], // Open path
    [x,y,x,y,x,y,...], // Closed path for a hole
    [x,y,x,y,x,y,...], // Closed path for outer shape #1
    [x,y,x,y,x,y,...], // Closed path for a hole
    [x,y,x,y,x,y,...], // Closed path for outer shape #2
    [x,y,x,y,x,y,...], // Open path
    [x,y,x,y,x,y,...], // Closed path for a hole
    ...
]
```

**Comment by tbfleming** [comment] 2016-12-08 14:52
It uses this for fill and stroke color: ```[r, g, b, a]```

**Comment by tbfleming** [comment] 2016-12-08 15:15
I'm attaching a path stress test. This path object mixes up open and closed paths.

[path stress.svg.txt](https://github.com/LaserWeb/LaserWeb4/files/639792/path.stress.svg.txt)

Here's how it behaves:
![path stress](https://cloud.githubusercontent.com/assets/418464/21015219/251779d4-bd2f-11e6-864c-7769c50dce2f.gif)

**Comment by lautr3k** [comment] 2016-12-08 15:30
Hum... In my head a path can not contain another path. The only case is to define the shape holes. Otherwise it is a group of paths. I would like to be able to select only one shape at a time.

**Comment by tbfleming** [comment] 2016-12-08 15:34
SVG path objects allow it. It's up to the user to decide when they create them.

**Comment by tbfleming** [comment] 2016-12-08 15:36
If SVG didn't support it, then path union operations would sometimes be invalid.

**Comment by lautr3k** [comment] 2016-12-08 15:40
Yes but if my parser gives you each item separately in a group, is not it better? Anyway that's how it works.

**Comment by tbfleming** [comment] 2016-12-08 15:40
I hate the placement of that stupid close button :)

**Comment by lautr3k** [comment] 2016-12-08 15:40
Me too !!!

**Comment by tbfleming** [comment] 2016-12-08 15:42
That would be fine, as long as it doesn't mess up complicated cases. I'll see if I can construct a case that may give grief when breaking up.

**Comment by tbfleming** [comment] 2016-12-08 16:22
[path stress 2.svg.txt](https://github.com/LaserWeb/LaserWeb4/files/639934/path.stress.2.svg.txt)

The existing parser handles this case, but poly2tri hits a limitation. I just pushed a workaround which skips filling the inside when poly2tri barfs. I may have to dump poly2tri for another library.

Here's what it should look like:

![image](https://cloud.githubusercontent.com/assets/418464/21017547/c1cf993e-bd37-11e6-8e65-dca6e8705776.png)

Here's what it actually looks like because of the poly2tri issue:

![image](https://cloud.githubusercontent.com/assets/418464/21017588/dedf4614-bd37-11e6-8d2b-c8b5ddc13580.png)

* Right way to break it up: turn it into a 7-point path and a 5-point path.
* Wrong way: two triangles.

**Comment by tbfleming** [comment] 2016-12-08 16:29
This test also exposed a bug in CAM that I'll track down.

What it does (wrong):

![image](https://cloud.githubusercontent.com/assets/418464/21018067/78d8a1c4-bd39-11e6-806b-89103258289b.png)

What it should do (jscut output):

![image](https://cloud.githubusercontent.com/assets/418464/21018084/8e1a2c88-bd39-11e6-94e4-7417b17fba7f.png)

**Comment by lautr3k** [comment] 2016-12-08 16:48
Ok, I understand. My parser interprets it as two triangles. I will work on that.

**Comment by tbfleming** [comment] 2016-12-08 17:51
The CAM bugs for Path Stress 2 are now fixed.

**Comment by tbfleming** [comment] 2016-12-08 17:55
Be aware that there's a really nasty numeric stability problem finding intersections within paths. Known algorithms that solve it are complex. Don't try the obvious algebraic equations; they backfire badly with certain border cases. Use Clipper instead.

**Comment by lautr3k** [comment] 2016-12-15 16:56
@tbfleming Just finished, when you have time, look at it
![lw svg-parser](https://cloud.githubusercontent.com/assets/796149/21233424/53e304e8-c2ef-11e6-8248-8518fee431b6.gif)

https://github.com/lautr3k/lw.svg-parser

**Comment by jorgerobles** [comment] 2016-12-15 17:06
Un***kBeleiveable.

**Comment by openhardwarecoza** [comment] 2016-12-15 17:07
Lol!  Yip @lautr3k 's work usually invokes that response (; amazing work
always

**Comment by tbfleming** [comment] 2016-12-15 18:23
@lautr3k es6 promises! nice!

**Comment by tbfleming** [comment] 2016-12-15 20:28
It's now integrated.

**Comment by cojarbi** [comment] 2016-12-15 20:34
+1 Jorge's comment

**Comment by jorgerobles** [comment] 2016-12-15 20:35
Let spoil the happiness, a bit...

`error: TypeError: Cannot read property 'replace' of undefined
    at TagParser._normalizeTagAttr (http://localhost:8080/index.js:132578:40)
    at http://localhost:8080/index.js:132546:32
    at Array.some (native)
    at TagParser._parseTagAttrs (http://localhost:8080/index.js:132540:40)
    at TagParser.parse (http://localhost:8080/index.js:132493:19)
    at Parser._parseElement (http://localhost:8080/index.js:131925:29)
    at http://localhost:8080/index.js:131868:39
    at Parser.parse (http://localhost:8080/index.js:131861:21)
    at http://localhost:8080/index.js:131855:41`

[test_ls3_paths.svg.zip](https://github.com/LaserWeb/LaserWeb4/files/655756/test_ls3_paths.svg.zip)

**Comment by tbfleming** [comment] 2016-12-15 20:37
Did you ```npm run installdev```? If so, you might need to wipe node_modules and rerun it.

**Comment by tbfleming** [comment] 2016-12-15 20:38
Never mind ```installdev```. I just reproduced it.

**Comment by tbfleming** [comment] 2016-12-15 20:40
I hold off pushing to https://laserweb.github.io/LaserWeb4/dist/

**Comment by tbfleming** [comment] 2016-12-15 20:45
test_ls3_paths.svg also fails at https://lautr3k.github.io/lw.svg-parser/dist/example/

**Comment by jorgerobles** [comment] 2016-12-15 20:51
It was running on the previous parser.

**Comment by lautr3k** [comment] 2016-12-15 22:18
Fixed with https://github.com/lautr3k/lw.svg-parser/commit/a6562f5aceb7ab46730dfd49cad6502009f44767 due to trailing ";" on style attribute.

**Comment by tbfleming** [comment] 2016-12-16 03:03
Updated. test_ls3_paths.svg exposes another issue. I use viewBox to transform the coordinates I get from Tag.paths. lw.svg-parser scrambles the viewBox values when these are present:

```
   width="100%"
   height="100%"
```

Please don't modify the viewBox values in lw.svg-parser; if you adjust the viewBox it then it will mess up the transform on my end.

**Comment by lautr3k** [comment] 2016-12-16 06:58
If you want the document Viewox use `parser.document.viewBox` instend of `tag.attr.viewBox` ;) Sorry not yet documented.

**Comment by lautr3k** [comment] 2016-12-16 07:08
After the main SVG was parsed you can access this two properties on the parser instance : 
`
parser.editor         // Editor info { name, version, fingerprint }
parser.document  // Document info { width, height, viewBox } 
                             // where viewBox is { x, y, width, height }
`
https://github.com/LaserWeb/lw.svg-parser/blob/master/src/parser.js#L14-L15

**Comment by lautr3k** [comment] 2016-12-16 07:38
Plus on from the Tag object you get two main functions : 
`tag.getPaths()` return an array of Path objects (all contours + holes)
`tag.getShapes()` return an array of ExPolygons objects from Clipper.js (filled shapes)

**Comment by lautr3k** [comment] 2016-12-16 08:29
Published on NPM ;) `npm install lw.svg-parser`

**Comment by jorgerobles** [comment] 2016-12-16 08:41
Badass!

2016-12-16 9:29 GMT+01:00 Sébastien Mischler (aka skarab) <
notifications@github.com>:

**Comment by lautr3k** [comment] 2016-12-16 11:17
Updated the `lw.svg-parser` module to v0.2.0 not a big change juste splitted code in smaller modules : 
`lw.svg-curves` and `lw.svg-path`. https://www.npmjs.com/~skarab

**Comment by tbfleming** [comment] 2016-12-16 22:59
What happened to paths? Yesterday the coordinates were in px; today I'm not sure what they are. They don't match px or mm.

**Comment by lautr3k** [comment] 2016-12-17 05:46
I did not touch anything at this level, I just split the code into several modules.

**Comment by lautr3k** [comment] 2016-12-17 08:01
@tbfleming please try to install from NPM `npm install lw.svg-parser --save` simpler for maintenance ;)

**Comment by tbfleming** [comment] 2016-12-17 11:33
@lautr3k It broke when I switched to the NPM package (coordinates messed up), so I didn't commit that.

**Comment by lautr3k** [comment] 2016-12-17 12:31
@tbfleming I think it was already like that before, but you have not seen it. I just saw it on a document with width/height set to 100%. Other documents with a fixed size seems correct... Can you confirm?

**Comment by tbfleming** [comment] 2016-12-17 15:39
Confirmed. It now uses the NPM package.

**Comment by lautr3k** [comment] 2016-12-17 16:18
More generally it crashes on relatives units. I'll try to fix it tomorrow.

**Comment by lautr3k** [comment] 2016-12-17 18:00
Finally done right now ;) Package updated. 

Test file : https://www.w3.org/TR/2011/REC-SVG11-20110816/images/coords/Units.svg
Demo : https://lautr3k.github.io/lw.svg-parser/dist/example/

**Comment by tbfleming** [comment] 2016-12-17 18:31
Confirmed fixed.

**Comment by tbfleming** [comment] 2016-12-19 20:34
@lautr3k Could you preserve image tags? You don't need to do any processing, the ```xlink:href="data:..."``` attribute matches the format I use to store images.

**Comment by lautr3k** [comment] 2016-12-19 21:59
@tbfleming you can access original element via tag.element

**Comment by tbfleming** [comment] 2016-12-19 22:08
@lautr3k it says skips them:

![image](https://cloud.githubusercontent.com/assets/418464/21330855/92e0f71a-c60d-11e6-8f31-00cd29e96b9a.png)

**Comment by lautr3k** [comment] 2016-12-19 22:10
Haaaa ok, understood, yes of course !

**Comment by lautr3k** [comment] 2016-12-19 22:12
Next year, promised I take English lessons.

**Comment by lautr3k** [comment] 2016-12-20 10:07
Done `<image>` and `<text>` tags ;)

**Comment by tbfleming** [comment] 2016-12-21 16:58
Image integrated:

![image in svg](https://cloud.githubusercontent.com/assets/418464/21398275/c7c4cb4c-c774-11e6-8c6e-ed7f9cc522f9.gif)

**Comment by cojarbi** [comment] 2016-12-21 17:04
Totally killer. Better workflow impossible

**Comment by maudette01432** [comment] 2016-12-21 17:37
This rocks.  Aside from the "laser diameter" not being a tool setting that gets auto populated from machine settings this is a highly workable work flow.  Not much room for improvement on the usability side.

**Comment by jorgerobles** [comment] 2016-12-21 20:54
Hmm.. I think "Laser Diameter" on Rasterizer should be called better "Line
Density". The minimum should be the Laser diameter setting, of course.

2016-12-21 18:37 GMT+01:00 maudette01432 <notifications@github.com>:

**Comment by tbfleming** [comment] 2016-12-21 21:06
@lautr3k I assume beamSize controls the distance between lines. Does it control anything else?

@jorgerobles There may be cases where you want the line distance to be less than the laser diameter; it may produce interesting effects.

**Comment by lautr3k** [comment] 2016-12-23 11:41
> @lautr3k I assume beamSize controls the distance between lines. Does it control anything else?

The `beamSize` need to be renamed `toolDiameter` to be right. It does not handle only the space between the lines, but also the offset (toolRadius) of start /end of line to stay in the shape. And add a `lineOffset` or `toolOffset` parameter to add a voluntary gap betwen lines without touching the size of the tool.

**Comment by lautr3k** [comment] 2016-12-23 11:43
New feature in the lab, I just changed the S by a Z, I work on multiple passes.
![lw raster-to-gcode](https://cloud.githubusercontent.com/assets/796149/21453209/3abf8b70-c90d-11e6-9325-f4ae1ee2b81f.gif)

**Comment by lautr3k** [comment] 2016-12-23 12:10
Would it be possible to add the possibility of opening a gcode file in lw4? I would like to take advantage of the simulator :)

**Comment by openhardwarecoza** [comment] 2016-12-23 13:07
(; @tbfleming yes please lot of existing lw3 users open gcode from other
apps like fusion360 etc sometimes... (and dxf too)

**Comment by lautr3k** [comment] 2016-12-23 15:21
Add invertColor setting, need to upgrade to `lw.raster-to-gcode@0.4.0`.

**Comment by tbfleming** [comment] 2016-12-23 16:26
![image](https://cloud.githubusercontent.com/assets/418464/21458221/b3a35284-c902-11e6-83be-c4d0b3e1ad22.png)

**Comment by iceblu3710** [comment] 2016-12-28 02:36
I have an SVG render gremlin. The parser skipped one `path` in my file and `line` does not render on screen at all. The `path` under shapes show up when selected but not the `line` items.

Source files:

[text_as_curves .svg.txt](https://github.com/LaserWeb/LaserWeb4/files/674930/text_as_curves.svg.txt)
![svg_issue_example](https://cloud.githubusercontent.com/assets/187394/21512504/dec1dfc0-cc73-11e6-9770-1acbb6bdb809.png)

Example issues:

![svg_issue_1](https://cloud.githubusercontent.com/assets/187394/21512417/0ccf3300-cc73-11e6-8c4d-fbc10101f454.png)
![svg_issue_2](https://cloud.githubusercontent.com/assets/187394/21512418/0cd39d50-cc73-11e6-9ac8-8d6e1f5c078d.png)

**Comment by tbfleming** [comment] 2016-12-28 03:45
Some trouble spots with this file, besides the parse error above:
* Based on viewbox + width + height it looks like it's 1,000 px per inch, which is very odd.
* It uses style tags, which we don't support. Since we see no fill or outline, we assign a fill. That doesn't help the open shapes.
* I just reproduced this bug with an SVG from Inkscape: the selection mechanism fails to highlight single lines and paths with only 2 points.

**Comment by iceblu3710** [comment] 2016-12-28 04:13
I have solved the missing `R` in my SVG. The parser does not like the letters grouped with the numbers in the paths. `0 z m 22` displays the letter while `0zm22` throws the error. That's a bit odd since `98c0` works just fine.

My viewbox is messed up as CorelDraw's export has a `precision` value and it rounds the internal values and is used to multiply the viewbox. I will need to look into its proper setting. Using `internal styling` removes the embedded css and properly displays all the lines, polylines, etc. I can select everything except single line and paths with 2 points.

**Comment by tbfleming** [comment] 2016-12-28 04:29
It creates a bitmap for hit testing. It uses similar code to paint both the selection and the hit test bitmap.

**Comment by tbfleming** [comment] 2016-12-28 16:56
I fixed the line and 2-point path issues.

**Comment by lautr3k** [comment] 2016-12-28 17:17
I'll fix the parser tomorrow.

**Comment by iceblu3710** [comment] 2016-12-29 03:06
I can confirm 2 point path and line issues are solved. Thanks!

**Comment by lautr3k** [comment] 2016-12-29 08:04
Fixed in lw.svg-parser@0.3.2

**Closed** 2017-01-13 19:58 UTC
Labels: PLEASE CODE
