### ISSUE TITLE
Laser intensity: E instead of S

### ISSUE THREAD

**Issue by Kriechi** [LaserWeb/LaserWeb4#451] opened 2018-01-23 22:27 UTC
Hi,

I'm using a DuetWifi and want to use the letter E instead of S to control the laser intensity.
But changing the machine setting for "LASER INTENSITY" has no effect on the generated g-code.

Other settings, like start/stop codes are correctly updated in the generated code.

**Comment by Kriechi** [comment] 2018-01-23 22:42
Reading a bit of source code tells me, that only `cam-gcode-laser-cut.js` makes use of this setting.
I tested it with a "Laser Cut" job - and it does indeed generate correctly.

Is it possible to also make this work with a "Laser Raster" job?

**Comment by tbfleming** [comment] 2018-01-24 04:18
Duplicate of #395

**Closed** 2018-01-31 19:20 UTC
