### ISSUE TITLE
Implementing A-Axes

### ISSUE THREAD

**Issue by cprezzi** [LaserWeb/LaserWeb4#304] opened 2017-05-13 14:28 UTC
Since I have added an A-axes to grbl-LPC, we also need to add it to LW4 ;)

I did add a "Machine A Stage" toggle switch to the machine settings (corresponding to "Machine Z Stage") and included the A-axes in the DRO including Jog buttons (only shown if the "A Stage" is active). 

Know, how do we want to show the A position on the workspace?

**Comment by cprezzi** [comment] 2017-05-13 14:30
If A is a rotary axes, we could map A to X or Y (depending on axis orientation). What do you think?

**Comment by jorgerobles** [comment] 2017-05-13 14:35
Good question.  Should we put a flat compass overlay on a workspace corner?
A position will rotate the compass. Could be an svg with css transform, no
webgl required...

**Comment by cprezzi** [comment] 2017-05-13 14:37
The question is also, how we can show the gcode in the workspace?

**Comment by jorgerobles** [comment] 2017-05-13 14:42
That's harder. @tbfleming?

**Comment by tbfleming** [comment] 2017-05-13 15:02
> Since I have added an A-axes to grbl-LPC, we also need to add it to LW4 ;)

I laughed when I read this. It implies that other firmware isn't worth it...

> The question is also, how we can show the gcode in the workspace?

This gets tricky:

1. The gcode spec says A is parallel to X. Do we hold to that spec and prevent users from positioning A differently?
1. We need a way to specify where the A axis is, unless we fix it to Y=0, Z=0. If we fix it there, then we enter Y negative space. Do we drop the recommendation that X, Y shouldn't go negative?
1. An A axis move turns a line into a curve. Option 1A: we could do this conversion before WebGL, which is easy to implement, easy to explain, but can slow down execution and adds a new segment length config. Option 1B: draw curves on the GPU, which takes us further down the path of no one else understanding the WebGL code.
1. I used a Smoothie-specific approach on the CAM side which changes the A units from degrees to mm on the cylinder surface. We probably need to drop that approach and switch it to degrees.

**Comment by cprezzi** [comment] 2017-05-13 16:11
@tbfleming You are right could be missunderstud ;) 
Was just meant that I am right in a flow...

**Comment by cprezzi** [comment] 2017-05-13 16:21
1. It's hard to prevent users from doing anything if you don't stand by their side ;)
2. We already dropped this recommendation by adding the workspace origin offset. This makes absolute sense for milling.
3. I'm a noob in this field.
4. Good question. What is the most used usecase for a rotary axes? Projection of a two dimensional vector grafic to the surface of a zylinder? That would at least be an good starting point. It would clearly be nice to show the zylinder projection in the workspace, but an easyer solution could be to just take A as Y (flat).

**Comment by jorgerobles** [comment] 2017-05-13 17:59
1.gcode spec
3. I would go for 1A for the moment. Adding a new segment length is not a big issue.
4. I should use the flat projection. If not, the cylinder has to be parametrized also.

:)

**Comment by tbfleming** [comment] 2017-05-13 18:00
Flat projection means we won't have to deal with curves and segment length.

**Comment by jorgerobles** [comment] 2017-05-13 18:02
Oh, I misread. Go for it :)

**Comment by tbfleming** [comment] 2017-05-13 18:50
Did the easy part 1st. The preview now adds A to Y. This comes out right for the existing CAM, but the scale will be off once the CAM switches A to degrees.

**Comment by tbfleming** [comment] 2017-05-13 20:13
Path CAM is now degrees. Untested.

**Comment by cprezzi** [comment] 2017-05-13 22:04
Can we reatch it somehow, that the A to Y scaling is 1:1? I mean, if the document shows 100mm in Y, then also A shows 100mm in grid Y?
How can I feedback the tool position? Could you add a A axis, or should I just feed A as Y?

**Comment by tbfleming** [comment] 2017-05-13 22:22
We need to make a choice: do we scale A to Y in the gcode preview to match mm on a cylinder, or do we scale A to Y in the gcode preview to be degrees?

**Comment by cprezzi** [comment] 2017-05-13 22:37
Good question. I think the first would lead to less questions from normal users, as this is what they expect when they engrave on a cylinder.

**Comment by jorgerobles** [comment] 2017-05-14 06:49
I would go for be easy for base user. Any professional guy should know what it's done and why (At least for a first approach)

**Comment by jorgerobles** [comment] 2017-05-14 07:05
One noob question. If I got my roller at the middle of the bed, say Y100 of 200, how do I move it to that position, then start to engrave over the cylinder, and how is that represented in a easy to user way?
I know using A is not noob task but I think is confusing right now isn't it? 
Indeed I made a roller a couple weeks ago, lying around and I'm dying to use it :D

**Comment by jorgerobles** [comment] 2017-05-14 07:12
Should we use Y axis machine offset to begin A projection?

![image](https://cloud.githubusercontent.com/assets/1706080/26031922/38d36498-3885-11e7-8c94-e199a80c69e7.png)

**Comment by cprezzi** [comment] 2017-05-14 10:20
I see the process like this:
1.  Jog to X/Y(/Z) origin of rotary axes.
2.  SetZero
3.  Start Job in X/A axis

With this process, the gcode should be in X+/Y+ quadrant. 
The workspace origin (can/should) represent the rotary axis origin position (XY).

**Comment by tbfleming** [comment] 2017-05-14 13:51
I've always been uneasy with shifting the grid. That screenshot reinforces my unease. gcode is in wpos so we should draw wpos.

**Comment by tbfleming** [comment] 2017-05-14 14:19
Here's how shifting the grid is biting us:
* I'm using drawnY = gcodeY + gcodeA.
* To correct for the grid I'd have to change it to drawnY = gcodeY + gcodeA + correction.
* The correction shifts it so that when gcodeY=0 and gcodeA=0 it appears on the grid's Y=0.

i.e. the way to fix the problem is to abandon mpos.

**Comment by jorgerobles** [comment] 2017-05-14 14:19
Many people don't have so abstract view and expect the workspace resemble their machine (a la reprap). Currently grid shifting is only visual :)

**Comment by tbfleming** [comment] 2017-05-14 14:20
It is only visual, but look at the confusion it causes when you don't position the rotary at MPos Y=0.

**Comment by cprezzi** [comment] 2017-05-14 14:21
@tbfleming You are kind of right. At the moment we mix wpos and mpos, as gcode relates to wco origin, but workspace has machine size!

**Comment by jorgerobles** [comment] 2017-05-14 14:23
We are f***up already :rofl:

**Comment by tbfleming** [comment] 2017-05-14 14:23
I'm starting to think of it this way:
* Users who understand mpos vs. wpos expect the grid to show wpos like other tools do.
* Users who don't understand mpos vs. wpos shouldn't ever monkey with mpos. They should drag the documents to the target position instead.

**Comment by cprezzi** [comment] 2017-05-14 15:13
What if we read the real work offset from the machine and move the work origin (including gcode) on the workspace to that location? The workspace total size would stay like it is and represent the machine size.
This would mean we just have to store additional work offsets in the workspace.

**Comment by jorgerobles** [comment] 2017-05-14 15:20
That idea came to my mind a while ago when included machine offset setting... I don't remember right now the issue when had mentioned​.

**Comment by tbfleming** [comment] 2017-05-14 15:26
> What if we read the real work offset from the machine and move the work origin (including gcode) on the workspace to that location? The workspace total size would stay like it is and represent the machine size.

This would still throw off the rotary position.

How about this?
* Grid, documents, and gcode preview all show wpos
* Grid goes positive and negative in both X and Y
* Grid size setting is separate from machine size setting
* A new set of markers would indicate machine bounds. They would move when the work origin changes.

Screen mock up:
![image](https://cloud.githubusercontent.com/assets/418464/26035295/041c727c-3898-11e7-9b85-306faf90f0d3.png)

**Comment by tbfleming** [comment] 2017-05-14 15:31
I didn't have negative area to work with when drawing that. Usually the lower-left marker would be at 0,0 or go into negative space.

**Comment by jorgerobles** [comment] 2017-05-14 15:40
I think that should work lovely and will teach mpos and wpos easy.

**Comment by tbfleming** [comment] 2017-05-14 15:59
Since the wpos origin would only affect the markers, it would be easy in the future to support machines where MPos 0,0 isn't the lower-left corner. Professional machines are often not like that, which is why GRBL isn't like that.

**Comment by tbfleming** [comment] 2017-05-14 16:28
@cprezzi I'm getting "error: undefined" with Set Zero on grbl-lpc

**Comment by tbfleming** [comment] 2017-05-14 18:28
I must be missing something. I got set zero to work, but it doesn't cause the grid to shift. I tried with both grbl and smoothie. @jorgerobles how do you shift the grid like in your screenshot?

**Comment by jorgerobles** [comment] 2017-05-14 18:29
Settings- machine - machine origin :)

**Comment by tbfleming** [comment] 2017-05-14 18:33
Ah. I thought grid shift was tied to the wpos origin. So right now users have to set up their wpos origin and type that value into the config separately?

**Comment by jorgerobles** [comment] 2017-05-14 18:36
Is unfinished  (or fake) right now only paints baselines in other positions
and coords numbering

**Comment by tbfleming** [comment] 2017-05-14 18:40
Is there a way to get the wpos origin?

**Comment by jorgerobles** [comment] 2017-05-14 18:52
Em nop that i know. Should be get from machine isn't it? Sorry i'm a bit
confused.

El 14 may. 2017 8:40 p. m., "Todd Fleming" <notifications@github.com>
escribió:

Is there a way to get the wpos origin?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/LaserWeb/LaserWeb4/issues/304#issuecomment-301331322>,
or mute the thread

**Comment by tbfleming** [comment] 2017-05-14 19:11
Yes. We need to get the wpos origin from the machine.

**Comment by tbfleming** [comment] 2017-05-14 20:00
Screenshot:

![image](https://cloud.githubusercontent.com/assets/418464/26037298/6f99f03a-38be-11e7-8fec-acee02ed0d73.png)

* Grid size controlled by: Settings -> Application -> Grid Width and Grid Height
* Machine size controlled by: Settings -> Machine -> Machine Width and Machine Height
* Machine position controlled by: Settings -> Machine -> Machine Origin X and Machine Origin Y
  * Temporary. It should be controlled by retrieving the WPos offset from the machine.

**Comment by jorgerobles** [comment] 2017-05-14 20:03
Cooool. :) Will test tomorrow

**Comment by tbfleming** [comment] 2017-05-14 20:24
Made it stand out more:

![image](https://cloud.githubusercontent.com/assets/418464/26037493/bba8f84c-38c1-11e7-8662-932dc22910ae.png)

**Comment by openhardwarecoza** [comment] 2017-05-15 10:21
I missed the comments that this thread also talked about the new grid size.  Sorry @jorgerobles 

Anyways,  to answer @cprezzi 's "The question is also, how we can show the gcode in the workspace?" in LW3 we had been working toward doing rotary preview like this: https://github.com/LaserWeb/deprecated-LaserWeb3/issues/51#issuecomment-236152662

![ffc69788-558b-11e6-8a47-119e761f7845](https://cloud.githubusercontent.com/assets/7695323/26053412/0e285d72-3969-11e7-961b-ebbf316e76e5.PNG)
![1e75a566-53ca-11e6-880f-35ee9b40abba](https://cloud.githubusercontent.com/assets/7695323/26053413/0e2deb8e-3969-11e7-8ce7-0965af1cbc09.PNG)

**Comment by cprezzi** [comment] 2017-05-15 13:53
@tbfleming We can get the work offset from the firmwares. It's just not programmed yet.

**Comment by cprezzi** [comment] 2017-05-15 13:57
@tbfleming Question: What sense does it make that the grid is shown bigger than the machine? The user is always limited by the machine size. Theoretically, the grid (virtual) space is infinite, but users are used that only the machine space is shown (Repetier, Cura, Mach3...).

**Comment by tbfleming** [comment] 2017-05-15 14:00
We could limit it to the machine size, or we could let the user choose.

**Comment by cprezzi** [comment] 2017-05-15 14:08
I can see a case, where the part is bigger than the machine. For this case, it's bether like it is now, so the user could see the whole part and the lilited machine space.

**Comment by cprezzi** [comment] 2017-05-15 14:18
Did you realize that I have removed the Z-axes DRO and Jog buttons, if Z-Stage is not active in machine settings? Same for A-axes. Is this ok for you?

**Comment by tbfleming** [comment] 2017-05-15 15:13
@cprezzi Makes sense to hide those.

**Comment by cprezzi** [comment] 2017-05-15 15:32
I have implemented the work offset in lw.comm-server (for smoothie yet) and in com.js. Grbl will follow.

**Comment by cprezzi** [comment] 2017-05-15 15:37
![grafik](https://cloud.githubusercontent.com/assets/5457949/26065757/3292f8ee-3995-11e7-8284-eb0ab6901afa.png)

**Comment by cprezzi** [comment] 2017-05-15 15:39
Now you can jog to the origin of your material, click 'set zero' and voila!

**Comment by jorgerobles** [comment] 2017-05-15 15:40
@cprezzi are you going to cut that box? If is from boxes.py I had hard time yesterday (#305) I have to determine if was the file or build prod env (reverted already)

**Comment by cprezzi** [comment] 2017-05-15 16:16
@jorgerobles That's just an old testfile I use. We drop some lines when they lay on top of others (like in the middle of left two parts on top). The gcode is correctly generated, if each part is a separate operation.

**Comment by cprezzi** [comment] 2017-05-15 16:17
Ok, now the grbl offset also works (needs to delete node_modules/lw.comm-server and run installdev).

**Comment by cprezzi** [comment] 2017-05-15 16:19
Max two days from idea to solution - not bad guys 🥇

**Comment by jorgerobles** [comment] 2017-05-15 16:20
Niiiice ;)

**Comment by cprezzi** [comment] 2017-05-15 16:22
How do we want to handle Z and A offsets? (not available yet in settings)

**Comment by cojarbi** [comment] 2017-05-15 16:22
I love having season tickets to watch this awesomeness!!!! you guys rock!!!!!

**Comment by tbfleming** [comment] 2017-05-15 16:25
Let's not represent Z and A offsets unless a use case comes up.

**Comment by jorgerobles** [comment] 2017-05-15 16:27
Will include `npm update lw.comm-server` on installdev script that will update dependency.

**Comment by cprezzi** [comment] 2017-05-15 16:29
@jorgerobles You probably need to allow Live Jogging to negative values now ;)

**Comment by jorgerobles** [comment] 2017-05-15 16:31
where are bed bounds calculated? I'll just use that bounds as limit.

**Comment by tbfleming** [comment] 2017-05-15 17:03
I split it up:
* Settings -> Machine -> Machine Left X and Machine Bottom Y: These set the X,Y coordinate of the bottom-left of the machine (MPos).
* Workspace now has workOffsetX and workOffsetY (not saved). com.js controls this.

**Comment by tbfleming** [comment] 2017-05-15 17:22
@jorgerobles This calculates the lower-left corner of the bed bounds: https://github.com/LaserWeb/LaserWeb4/blob/bf8d2a19d40b1c8824a42396c5c7387a15391600/src/components/workspace.js#L559

**Comment by jorgerobles** [comment] 2017-05-15 19:39
hmm live jogging goes nuts. It's twitchy. Seems to go to a point and then go back and then forth.

**Comment by jorgerobles** [comment] 2017-05-16 06:23
@cprezzi, @tbfleming  Does this feel right? Is this the intended behaviour? Correct me if wrong, 
`I'm one of those` :trollface: 

- Expected the bed to be fixed on place when cursor moves. 
- Once you have used Set Zero, then coordinates fixes to that place. Isn't it?
- Livejogging works moving the cursor to a place in bed (just to mimic the CorelLaser jogging when placing artwork)
- Some bump glitches and flickering when moving.

![livejogging](https://cloud.githubusercontent.com/assets/1706080/26092077/410b8b82-3a0f-11e7-8bcc-e0a49d4a5483.gif)

**Comment by cprezzi** [comment] 2017-05-16 13:15
The result is theoretically the same, but it feels weired whenthe machine moves, instead of the cursor.

**Comment by jorgerobles** [comment] 2017-05-16 13:23
Hmm, should be but the coord numbers are not moving reflecting the cursor position (as the gif cursor pos is X0 Y0 always, what is not true :| )

**Comment by jorgerobles** [comment] 2017-05-16 13:24
And think on our poor users... :smile:

**Comment by cprezzi** [comment] 2017-05-16 14:13
Live Jogging was working fine for me before the last changes from Todd with the workOffsets ;)

**Comment by tbfleming** [comment] 2017-05-16 14:43
com.js controls both the workPos (purple marker) and workOffset (moves white area). The workspace draws what you tell it to :)

**Comment by tbfleming** [comment] 2017-05-16 15:51
Here's an option: I could move the camera with the machine. It would look like the machine is stationary but everything else (cursor, documents, grid) was moving. It won't solve the jumping; com.js has to figure out a way to keep everything in sync.

**Comment by cprezzi** [comment] 2017-05-16 16:13
@tbfleming Can you explain how the relations between camera position, workspace (grid), machine space and cursor exactly is?

I would expect that the machine is the anchor, the work origin has an offset to the machine origin and the cursor has an offset to the work origin. The camera would be movable but init to the center of the machine space.

Is that wrong?

**Comment by tbfleming** [comment] 2017-05-16 16:27
The entire coordinate system is in WPos. machineBottomLeft{X,Y}, workPos{X,Y}, and machine{Width,Height} control where the machine is drawn. workPos* control where the purple marker is drawn. The camera controls the transform between WPos and screen coordinates. If I make the camera move with the machine, then it will appear like the machine is anchored.

**Comment by tbfleming** [comment] 2017-05-16 16:33
Corrected above. We should probably rename workPos since it's not related to the wpos/mpos transform. spindlePos? cursorPos? markerPos?

**Comment by jorgerobles** [comment] 2017-05-16 16:40
Cursorpos :+1:

**Comment by cprezzi** [comment] 2017-05-16 19:06
cursorPos is fine for me too 👍

**Comment by tbfleming** [comment] 2017-05-16 23:01
![camera](https://cloud.githubusercontent.com/assets/418464/26131778/11e02d76-3a6a-11e7-87fb-5d86c0421ab4.gif)

**Comment by jorgerobles** [comment] 2017-05-17 06:00
Perfect! Great work!

**Comment by jorgerobles** [comment] 2017-05-17 10:56
Uhm.. @tbfleming, @cprezzi, I cannot get the cursor to move. I'm using a grbl1.1f on 328p, and behaves same as yesterday. What could it be? (It's updated of course)

**Comment by cprezzi** [comment] 2017-05-17 12:05
@jorgerobles Did you eventually forget to set $10=1?

**Comment by jorgerobles** [comment] 2017-05-17 12:08
nup.. $10=1

**Comment by jorgerobles** [comment] 2017-05-17 12:09
works ok with $10=0 :)

**Comment by cprezzi** [comment] 2017-05-17 14:41
It is in the docs on cncpro.co (see http://cncpro.co/index.php/31-documentation/initial-configuration/firmware/grbl-1-1e bottom right "configure GRBL settings" bold **$10=0**) :)

**Comment by jorgerobles** [comment] 2017-05-17 14:42
hoHohoho!!!

A big RTMF for me, thanks!!!!

**Comment by jorgerobles** [comment] 2017-05-25 06:46
Is any further work to keep this issue open?

**Comment by tbfleming** [comment] 2017-05-25 12:43
Someone needs to test the CAM A axis support on GRBL + Smoothie

**Comment by cprezzi** [comment] 2017-05-26 09:29
For testing A-axes on grbl-LPC my extended branch https://github.com/cprezzi/grbl-LPC/tree/more-axis is needed. 
Just tell me if anybody needs a firmware.bin with a specific configuration for testing.

**Comment by jorgerobles** [comment] 2017-05-26 09:37
@cprezzi  I do. I have a weird config, will change with the new C3Dboard, but just to test  

`laser_module_pin                             1.23o!  `

Thats open drain inverted. Is that possible?

**Comment by cprezzi** [comment] 2017-05-26 10:17
@jorgerobles At least the pin is supported. What do you mean with inverted? No mosfet that inverts? Usualy the Mosfets on pin 2.4 or 2.5 are used, so no inverting is needed.

**Comment by jorgerobles** [comment] 2017-05-26 10:19
Inverts the PWM regime, so is LO active rather than HI 
http://smoothieware.org/blue-box-guide?s[]=invert&s[]=pwm

**Comment by tbfleming** [comment] 2017-05-26 14:35
@jorgerobles what type of laser? How do you have it wired? Are you using a mosfet?

**Comment by jorgerobles** [comment] 2017-05-26 14:43
It's the k40, no mosfet, but a level shifter to drive L works like a charm. But I'm just wiring it to the 2.5 pin, so don't worry thanks :+1:

**Comment by tbfleming** [comment] 2017-05-26 15:46
Ah, the old approach people used to recommend before someone noticed a better way. grbl-lpc doesn't support that.

**Comment by funinthefalls** [comment] 2017-05-27 03:13
I am not sure that the old way is inferior, just different. I have not done any serious testing, however, I have one wired the old way and one wired the new way, and I do not really notice any real difference between the methods in the quality of engraving or cutting. And if you are running without a POT (I have a third one like that) it is actually better the old way because  tying the original variable voltage POT signal to constant 5V will actually swamp the PWM signal when pulsing L , and it becomes difficult to accurately control the power percentage.

**Comment by jorgerobles** [comment] 2017-05-27 20:34
Well, I've got A axis wired and some GRBL setup problems solved. Thanks @cprezzi :heart:
Now, being A in mm, having a 0.9deg/step motor and 1:2 reduction, what do I have to change on config? that's 400x2x16 steps by revolution...  Are A axis steps/deg?

**Comment by tbfleming** [comment] 2017-05-27 20:37
A is steps per degree

**Comment by tbfleming** [comment] 2017-05-27 20:40
Speed and acceleration limits are degrees/s and degrees/s^2

**Comment by jorgerobles** [comment] 2017-05-28 11:14
Well, shit happens, my brand new reprap A stage takes more space than available to put a regular drinking glass :| I could take off lens shroud as glass does not smoke like other materials, but will be defocused. Using Shot glass is not solution, slip thru the wheels.

-Solution 1: Redesign the A axis. just make it lower and redesign idle part too.
-Solution 2: cut down the bottom of the k40 case. It's workable, because could be used to clean bits of previous works. A removable steel sheet  could be put instead (just to not to burn table below)

On the Dev side, we have not implemented raster rescaling nor postprocessor to make raster2gcode works with it. Fail!

**Comment by jorgerobles** [comment] 2017-05-28 19:20
@tbfleming please could you take a look to https://github.com/LaserWeb/LaserWeb4/commit/8c75309de60ec69539546dc03dd833fe0adadbc7
for any errors? Seems working well, but maybe I've slip some maths.

**Comment by tbfleming** [comment] 2017-05-28 19:47
@jorgerobles the scale looks correct. The feed will be off in diagonal mode.

**Comment by jorgerobles** [comment] 2017-05-28 19:58
Yes. Diagonal mode is tricky. I let it to professionals ;)

**Comment by tbfleming** [comment] 2017-05-28 20:09
Since it's a fixed angle (45 deg) you can just divide the feed by sqrt(2).

**Comment by jorgerobles** [comment] 2017-06-05 17:15
@cprezzi Should we enable Livejogging if used setZero for people that not have endstops?

**Comment by openhardwarecoza** [comment] 2017-06-05 17:16
Yes please (:

**Comment by jorgerobles** [comment] 2017-06-05 17:25
[As you wish ](http://gph.is/2epojrO)

**Comment by cprezzi** [comment] 2017-06-05 21:43
Wha not. Just remember that without homing the displayed machine space will be offset to the real machine space, so there is a risk to livejogging the head into the axes ends! But the same risk exists with the jogging buttons, so no big difference.

**Comment by tbfleming** [comment] 2017-06-11 14:30
Has anyone tried the A axis support?

**Comment by jorgerobles** [comment] 2017-06-11 14:37
Tried but couldn't. I'll try to build a better fit rotary :)

Could we ask to jim fong?

**Comment by tbfleming** [comment] 2017-06-11 14:39
> Could we ask to jim fong?

Go ahead. It looks like he's on Smoothie and willing to try grbl-lpc. It'd be nice if he could test A axis on both.

**Comment by jorgerobles** [comment] 2017-06-11 14:49
Done :)

**Comment by jorgerobles** [comment] 2017-06-15 16:14
Jim Fong has the rotary setup for us, at https://plus.google.com/u/0/113562432484049167641/posts/XVv6a71HZtt?cfem=1

@tbfleming could you please take a look on his questions?

**Comment by jimfong1** [comment] 2017-06-15 16:40
Jorge asked me to post my questions here so I made a github account....

I have the rotary attached again to the laser which is currently running Smoothie.

**Comment by jimfong1** [comment] 2017-06-15 16:48
Ok I have the rotary back in the laser.  I noticed laserweb4 changed the configuration a bit.  There is no "A Resolution" setting anymore so I assumed it is now using the config.txt A-axis setting. I changed that to match my rotary.  It calculates out to be 195.55 steps per degree

Thanks for putting in A-axis jog buttons. Labels should be changed from mm to degrees.  Jogging "360mm" does move the rotary one full revolution.  That seems to be correctly configured. 

What does "segment" under rotary setup actually do. 

What do you need me to test??

**Comment by jimfong1** [comment] 2017-06-15 16:52
The "A diameter" setting doesn't seem to calculate the path right.  I use 25mm which is the diameter of the piece of wood I am engraving.  The resultant gcode image is really elongated and the rotary movements reflect that.  

Laserweb4 4.0.734

This worked right when I initially did the rotary test.

**Comment by jorgerobles** [comment] 2017-06-15 16:52
Segment is the minimum segment length allowed to a poly. Some controllers choke if segment is too small.

**Comment by tbfleming** [comment] 2017-06-15 16:52
"segment" is a lower bound on G1 length. It's to prevent the firmware from chocking on too many tiny moves.

**Comment by tbfleming** [comment] 2017-06-15 16:55
The viewer doesn't scale A-to-Y correctly yet. Right now I'm concerned with what happens when controllers run the generated gcode.

> The "A diameter" setting doesn't seem to calculate the path right. I use 25mm which is the diameter of the piece of wood I am engraving. The resultant gcode image is really elongated and the rotary movements reflect that.

Could you try a simple vector op? e.g. maybe a "Laser Cut" on a square sized to fit on your cylinder. It should be easier to diagnose.

**Comment by jimfong1** [comment] 2017-06-15 17:41
Test cut

Stock diameter 30mm. Set A diameter to 30
Draw a 94.2mm line. (3.14x30)
Rotary will move and cut a line one full revolution.  That is good. 

Things I've noticed. 
On the control screen A axis always display NaN

**Comment by tbfleming** [comment] 2017-06-15 17:47
It looks like it's just raster that's off.

**Comment by jimfong1** [comment] 2017-06-15 18:12
The set zero button doesn't set the rotary zero position.  

If I jog the rotary and hit the set zero button so I can place the image on another part of the stock, it doesn't cut it there.  It cuts it at the original machine coordinates again.

**Comment by jorgerobles** [comment] 2017-06-15 18:21
@tbfleming before the rotate feature, the gcode was generated that way (I mean, both vectors and raster were generated to Y+) 

In 0,0 I've got this result:
![image](https://user-images.githubusercontent.com/1706080/27195615-b73c092a-5207-11e7-80ad-6db3d48c4028.png)

And in 0, -150 this one:
![image](https://user-images.githubusercontent.com/1706080/27195680-f5f4145a-5207-11e7-9236-6a8ab9df3430.png)

Why? (workspace attached [a_test.json.txt](https://github.com/LaserWeb/LaserWeb4/files/1078565/a_test.json.txt))

**Comment by tbfleming** [comment] 2017-06-15 21:03
@jorgerobles your test case exposes the problem.

* Right now the gcode preview doesn't compensate for diameter, so:
  * Y=100 means 100mm, or
  * Y=100 means A=100 deg
* When you move both the rect and image so their bottoms are at Y=0mm and tops are at Y=30mm, everything lines up:
  * Raster gcode draws from Y=0 to ~115 deg
  * Rect gcode draws from Y=0 to ~115 deg
  * This corresponds to the document objects which range from Y=0 to Y=30mm
* If you move the rect and image so their bottoms are at Y=30mm, this should move the bottoms of the gcode to Y ~115 deg
  * Raster gcode bottom draws Y ~30 deg (bad)
  * Rect gcode bottom draws at Y ~115 deg (good)

**Comment by tbfleming** [comment] 2017-06-16 02:21
New control:

![image](https://user-images.githubusercontent.com/418464/27209309-f709afec-5218-11e7-92a5-842367edd51e.png)

**Closed** 2017-09-02 15:05 UTC
Labels: PLEASE TEST
