### ISSUE TITLE
Google Chrome timeout and progress

### ISSUE THREAD

**Issue by opaque01** [LaserWeb/LaserWeb4#152] opened 2017-02-12 23:54 UTC
I tried to generate GCODE and Chrome won´t react. If I don´t open activity view, I don´t know if chrome (LaserWeb4) is still working.

Is it possible to change the timout message (wait - close)?
Is it possible to show a progress bar?

greetings opaque

![activity](https://cloud.githubusercontent.com/assets/5427993/22867352/cfa81cf6-f186-11e6-80b8-639706757fd5.png)
![generating](https://cloud.githubusercontent.com/assets/5427993/22867353/cfaede6a-f186-11e6-84d4-b65f59cb0d83.png)
![waiting](https://cloud.githubusercontent.com/assets/5427993/22867354/cfafa37c-f186-11e6-920d-a0333382c44a.png)
![timeout](https://cloud.githubusercontent.com/assets/5427993/22867355/cfb2ad4c-f186-11e6-8d43-23728f46ecc2.png)

**Comment by tbfleming** [comment] 2017-02-13 00:09
Duplicate of #141, which is implemented for bitmaps, but not yet for vectors

**Comment by tbfleming** [comment] 2017-02-17 16:02
Reopening since #141 was closed

**Comment by jorgerobles** [comment] 2017-02-17 16:14
@opaque01, please attach source file and workspace json
@tbfleming what would be the best way to "progressize" the vector operations?

**Comment by tbfleming** [comment] 2017-02-17 16:22
Create a web worker to call getLaserCutGcodeFromOp() and getMillGcodeFromOp(). You'll have to create a way for the web worker to communicate with the main thread.

**Comment by jorgerobles** [comment] 2017-02-18 20:31
@tbfleming I've done tests, and doubt webworker will do anything. It makes the processor run on his own thread, but the thread could stall equally on large computations. So I'm going for the setTimeout 0 hack, but need to know where to "slice" the code to run.

I've seen a lot of loops and whiles in cam-gcode-mill. As I don't fully understand all the operations done there, please tell me the lines ideal to be splitted for recurrent function calls.

**Comment by tbfleming** [comment] 2017-02-18 20:42
Part of the code is C++ compiled to javascript; the setTimeout 0 hack won't work for those parts. e.g. the entire v-carve algorithm is in C++. The setTimeout hack leads to confusing code, especially for complicated algorithms like the CAM has. It's best to avoid it.

There's an advantage to webworkers: long runs don't hurt the UI thread. A cancel button can kill a webworker (worker.terminate()) if the user decides it's been running too long. Also, Chrome normally doesn't complain about busy webworkers.

**Comment by jorgerobles** [comment] 2017-02-18 20:59
@tbfleming Current issue will not be solved if we have a 100% process hogging the cpu. Also, yesterday I let a simple carve (not vcarve) with an overstep of 0.1 for 2 hours and was still hung. No UI interference (I left the computer alone and sad, an busy)
Also, if hung, no progress will be sent to the main process so apart the moving UI, the gcode will not be generated (though be cancelled)

Any ugly code could be refactored when manageable portions get achieved. I like to do things well, but better things working.
Please, if you could tell me where will be the best place to start slicing the code, at cam-gcode-mill.js:77, 90 or 112.... or other

**Comment by jorgerobles** [comment] 2017-02-18 21:00
@lautr3k, could you implement an stop method to lw.raster-to-gcode? thanks

**Comment by tbfleming** [comment] 2017-02-18 21:14
> Current issue will not be solved if we have a 100% process hogging the cpu

It will solve it:
* The UI won't freeze
* Chrome won't open a terminate-or-wait dialog
* The user can cancel without having to kill and reload the page

> Any ugly code could be refactored when manageable portions get achieved

The SetTimeout 0 hack turns code inside-out, making it hard to understand. The CAM code already takes a lot of effort to understand. Applying SetTimeout 0 to it will make it much harder.

**Comment by jorgerobles** [comment] 2017-02-24 19:57
@lautr3k working on this, seems Webworkers cannot operate DOM :| . lw-rastertogcode cannot be converted to use webworkers unless refactor and accept a Binary bitball of the image.

**Comment by jorgerobles** [comment] 2017-02-24 20:07
@tbfleming if have to move  getLaserCutGcodeFromOp() and getMillGcodeFromOp() to webworker, they have to show send a progress message (in any of the former lines)

**Comment by tbfleming** [comment] 2017-02-24 20:12
@jorgerobles they can use postMessage()

**Comment by jorgerobles** [comment] 2017-02-24 20:20
Yes.. on which line is better? (77...) 😏

**Comment by tbfleming** [comment] 2017-02-24 20:23
Let's focus on getting it working first. 0% at beginning and 100% at end.

**Comment by jorgerobles** [comment] 2017-02-24 21:09
@tbfleming some CAM operations or dependencies (snap?) rely on DOM, window, or regular process. 
Cannot be used on webworkers. https://github.com/LaserWeb/LaserWeb4/tree/webworkers

**Comment by tbfleming** [comment] 2017-02-25 04:47
@jorgerobles I pushed a fix to the webworkers branch.

**Comment by jorgerobles** [comment] 2017-02-25 08:13
Webworking! (pun intended at https://github.com/LaserWeb/LaserWeb4/commit/4f5040243ca7b83aad3755c6549e183d7f5dfa66)

**Comment by jorgerobles** [comment] 2017-02-25 16:29
@tbfleming examineDocTree moved to webworker.

**Comment by tbfleming** [comment] 2017-02-25 23:13
@jorgerobles examineDocTree works with images; it can't move to a webworker.

**Comment by lautr3k** [comment] 2017-02-26 07:12
My first commit used webworker and @tbfleming asked me to remove this feature...

**Comment by jorgerobles** [comment] 2017-02-26 08:40
@tbfleming I've ported that to webworker late night. It works well. I will merge branch today if lw-raster2gcode PR is solved. 

Checkout https://github.com/LaserWeb/LaserWeb4/tree/webworkers for testing before commit.

@lautr3k I've done a pull request to lw-rasterizer, implementing terminate to emulate a webworker, please check before commit. Now I'm using my own fork, I prefer yours :smile:

@lautr3k Also, the webworking issue of raster is the manipulation of Image done in lw-canvasgrid. If lw-canvas-grid have a method to convert to bitball on the main thread and then use the bitball on webworker thread instead "image" will work.

**Comment by tbfleming** [comment] 2017-02-26 08:43
The CAM didn't have a job management queue yet, so couldn't handle it. If I remember right, you kept it as an option.

**Comment by jorgerobles** [comment] 2017-02-26 08:45
@tbfleming I was meant for me? I did not understand. There's a job queue now for handling webworkers.

**Comment by tbfleming** [comment] 2017-02-26 08:46
Sorry, I meant @lautr3k

**Comment by jorgerobles** [comment] 2017-02-26 21:07
Merged and live! Will improve on @lautr3k works about webworkers.

**Comment by jorgerobles** [comment] 2017-02-28 07:48
@opaque01 should be working now as expected.

**Closed by jorgerobles** 2017-02-28 07:48 UTC
