### ISSUE TITLE
Webcam: Transformation Filters (v4.2.x targetted release)

### ISSUE THREAD

**Issue by ghost** [LaserWeb/LaserWeb4#222] opened 2017-03-18 11:39 UTC
Advanced functionality to extend #30 

#191 Note:  Moving this advanced task to its own issue - will be addressed here, when the time is ripe!

**Comment by openhardwarecoza** [comment] 2017-04-17 14:32
@raabrp is working on this...

**Comment by raabrp** [comment] 2017-04-18 00:41
Missed this comment when it was posted, sorry. I'll be sure to post as this goes forward. I'm approaching this somewhat casually, so I hope I'm not holding up anyone else.

**Comment by openhardwarecoza** [comment] 2017-07-31 20:09
Closing this issue for now - months since anyone thought of it

**Comment by jorgerobles** [comment] 2017-07-31 21:27
Just keep it open during summer :)

**Comment by jorgerobles** [comment] 2017-08-03 09:49
@tbfleming I'm taking a look to the code DarklyLabs made to backport to the current LW codebase.
All the drawcommands work is done, but I've got an issue, not directly related with that.

Cannot get a webgl context with canvas.getContext once a previous 2d context has been created on that canvas. Do you know any workaround?

**Comment by tbfleming** [comment] 2017-08-03 09:57
@jorgerobles that limit's part of the canvas spec. Only workaround is to create a new canvas.

**Comment by jorgerobles** [comment] 2017-08-03 09:58
Ok then :)

**Comment by tbfleming** [comment] 2017-08-03 10:02
Canvas has a transparent background; you can overlay one over the other when you need both 2D and 3D at the same time.

**Comment by jorgerobles** [comment] 2017-08-03 11:52
@tbfleming Ok, I've managed to get WebGL context on VideoPort. now I've got this:

![image](https://user-images.githubusercontent.com/1706080/28920623-df582896-7852-11e7-8130-deb9d0201ae5.png)

https://github.com/LaserWeb/LaserWeb4/blob/camera_fx/src/lib/webcam-fx.js
Any clue?

**Comment by tbfleming** [comment] 2017-08-03 12:43
I tried to reproduce, but got this:

```
Module not found: Error: Cannot resolve module 'aruco-marker' in C:\Users\Todd\Desktop\LW\LaserWeb4\src\components
```

Is everything pushed?

**Comment by jorgerobles** [comment] 2017-08-03 12:47
aruco-marker is on package.json 😮

**Comment by tbfleming** [comment] 2017-08-03 12:57
So it is. And it's in my node_modules. odd.

**Comment by tbfleming** [comment] 2017-08-03 13:00
webpack's acting very bizarre with this:

```
C:\Users\Todd\Desktop\LW\LaserWeb4\node_modules\aruco-marker doesn't exist
```

but this works:

```
C:\Users\Todd>dir C:\Users\Todd\Desktop\LW\LaserWeb4\node_modules\aruco-marker
 Volume in drive C has no label.
 Volume Serial Number is 02AF-E41B

 Directory of C:\Users\Todd\Desktop\LW\LaserWeb4\node_modules\aruco-marker

08/03/2017  08:37 AM    <DIR>          .
08/03/2017  08:37 AM    <DIR>          ..
08/03/2017  08:37 AM                12 .npmignore
08/03/2017  08:37 AM                 5 .tern-port
08/03/2017  08:37 AM                81 .travis.yml
08/03/2017  08:37 AM             2,731 aruco-marker.js
08/03/2017  08:37 AM               270 bower.json
08/03/2017  08:37 AM    <DIR>          build
08/03/2017  08:37 AM               157 CHANGELOG.md
08/03/2017  08:37 AM    <DIR>          demos
08/03/2017  08:37 AM             1,951 Gruntfile.js
08/03/2017  08:37 AM             1,059 MIT-LICENSE.txt
08/03/2017  08:37 AM               991 ng-aruco-marker.js
08/03/2017  08:37 AM             2,553 package.json
08/03/2017  08:37 AM             2,987 README.md
08/03/2017  08:37 AM    <DIR>          test
              11 File(s)         12,797 bytes
```

**Comment by jorgerobles** [comment] 2017-08-03 13:01
O_o  
Maybe has to be related with the use of require for instancing :|
`export const ArMarker=require('aruco-marker');`

**Comment by tbfleming** [comment] 2017-08-03 13:09
false alarm. An old server process was still running on my machine; they don't always die when I exit my editor.

**Comment by tbfleming** [comment] 2017-08-03 14:02
Here's what's happening:
* first time through: canvas.getContext, create DrawCommands, dispose DrawCommands
  * dispose DrawCommands disables the gl context to free all its resources
* second time through: canvas.getContext
  * oops. That context is already disabled

You need to hold onto DrawCommands as long as the canvas exists. You need to dispose it when the canvas goes away (hot reload or tab change).

**Comment by jorgerobles** [comment] 2017-08-03 14:10
Thanks!!

**Comment by jorgerobles** [comment] 2017-08-05 08:40
@tbfleming Could Please, Could We have an alpha parameter on `image` drawCommand

**Comment by tbfleming** [comment] 2017-08-05 11:44
@jorgerobles done

**Comment by jorgerobles** [comment] 2017-08-05 11:48
Love it! Thanks

**Comment by jorgerobles** [comment] 2017-08-05 11:48
Oye

**Comment by tbfleming** [comment] 2017-08-05 11:50
![image](https://user-images.githubusercontent.com/418464/28995261-c1aca482-79b2-11e7-890c-354d1139a540.png)

**Comment by jorgerobles** [comment] 2017-08-05 11:52
Hahah!

**Comment by domenic-d** [comment] 2018-01-22 08:36
Closed due to this being a very specific requirement for our machine and we no longer need it.

**Closed by domenic-d** 2018-01-22 08:36 UTC
Labels: enhancement, feature request
