### ISSUE TITLE
object not visible

### ISSUE THREAD

**Issue by opaque01** [LaserWeb/LaserWeb4#151] opened 2017-02-12 19:59 UTC
Why are some objects not visible in LaserWeb4. Path is closed and has the same color.
Screenshots: https://plus.google.com/111079322062040624414/posts/EuTK3aQHhE3
[super_who_locked.svg.zip](https://github.com/LaserWeb/LaserWeb4/files/769584/super_who_locked.svg.zip)

Maybe it is the same issue like: https://github.com/LaserWeb/LaserWeb4/issues/146

best regard
opaque

**Comment by tbfleming** [comment] 2017-02-12 20:29
Duplicate of #146

**Closed by tbfleming** 2017-02-12 20:29 UTC
Labels: duplicate

**Comment by tbfleming** [comment] 2017-02-12 20:53
Here's how it appears now with the workaround for #146:

![image](https://cloud.githubusercontent.com/assets/418464/22865902/123a899c-f13b-11e6-8fce-c1c5e7f991b0.png)

The bug and the workaround only affect the display. The CAM is OK with this file.
